name: envppb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - aset/img/
  fonts:
  - family: coco
    fonts:
    - asset: aset/font/coco.ttf
      weight: 400
    - asset: aset/font/coco-italic.ttf
      weight: 400
      style: italic
    - asset: aset/font/coco-bold.ttf
      weight: 700
